### ISSUE TITLE
a11y improvements

### ISSUE THREAD

**Issue by davidrojom** [biznaga-fest/web#12]
do you mind fixing this @josanri?
![image](https://github.com/user-attachments/assets/a7b3a7da-c545-4152-af3a-7ffaf08ad53e)

**Comment by josanri** [comment]
Okay, not sure if a dark mode button should be visible, as it makes no sense for someone without vision. I think I can fix both of these:
![image](https://github.com/user-attachments/assets/d65fd9d5-5f00-4b18-b515-29405f4fdb52)

**Comment by davidrojom** [comment]
this as well, please
![image](https://github.com/user-attachments/assets/0af2b26e-0b5e-461d-8248-3188e86f48d7)
